server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  rabbitmq:
    host: ${RABBITMQ_SERVICE_HOST}
    port: ${RABBITMQ_SERVICE_PORT}
    username: guest
    password: guest

security:
  user:
    name: gavin
    password: gavin

management:
  security:
    enabled: false
