server:
  port: 9104

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: schema_product
  drop-first: false
  enabled: true

spring:
  cloud:
    stream:
      bindings:
        cancel_reservation_input:
          binder: rabbit
          destination: cancelReservation
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3

---
spring:
  profiles: development

---
spring:
  profiles: test