spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schema_point?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1