server:
  port: 9103

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: schema_address
  drop-first: false
  enabled: true

---
spring:
  profiles: development

---
spring:
  profiles: test