server:
  port: 8000

zuul:
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie,Authorization
  retryable: true
  routes:
    oauth:
      path: /uaa/**
      service-id: oauth
      strip-prefix: false
    user:
      path: /users/**
      service-id: user
      strip-prefix: false
    address:
      path: /addresses/**
      service-id: address
      strip-prefix: false
    point:
      path: /points/**
      service-id: point
      strip-prefix: false
    product:
      path: /products/**
      service-id: product
      strip-prefix: false
    order:
      path: /orders/**
      service-id: order
      strip-prefix: false
    payment:
      path: /payments/**
      service-id: payment
      strip-prefix: false
    delivery:
      path: /deliveries/**
      service-id: delivery
      strip-prefix: false

logging:
  level:
    org.springframework.security: DEBUG

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: /users/activation,/uaa/oauth/token/**

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 80000

---
spring:
  profiles: development

security:
  oauth2:
    client:
      client-id: zuul
      client-secret: secret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token

---
spring:
  profiles: test

security:
  oauth2:
    client:
      client-id: zuul
      client-secret: secret
      access-token-uri: http://oauth:9999/uaa/oauth/token
      user-authorization-uri: http://oauth:9999/uaa/oauth/authorize
    resource:
      token-info-uri: http://oauth:9999/uaa/oauth/check_token