spring:
  application:
    name: eureka

management:
  security:
    enabled: false

---
spring:
  profiles: development

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 10

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-2:8762/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka-2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka/